id: 93fda2caae3c4d27b99f1fa2a43aef4a
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_846-Threefold_Invocation_Ritual-v2
  language: bo
  author: ''
  volume: {}
